name: Build and test

on: [push, pull_request]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack localhost
        run: ./up.sh
        if: always()
      - name: Run integration API tests
        run: cd tests && go build . && ./tests
        if: always()
      - name: print relevant logs (videoservice)
        run: docker logs $(docker ps | grep "videoservice" | awk '{print $1}')
        if: always()
      - name: print relevant logs (userservice)
        run: docker logs $(docker ps | grep "userservice" | awk '{print $1}')
        if: always()
      - name: print relevant logs (scheduler)
        run: docker logs $(docker ps | grep "scheduler" | awk '{print $1}')
        if: always()
      - name: print relevant logs (postgres)
        run: docker logs $(docker ps | grep "postgres" | awk '{print $1}')
        if: always()
      - name: print relevant logs (frontapi)
        run: docker logs $(docker ps | grep "frontapi" | awk '{print $1}')
        if: always()
      - name: print relevant logs (nginx)
        run: docker logs $(docker ps | grep "nginx" | awk '{print $1}')
        if: always()
      - name: Push images
        run: ./push.sh
